# Generated by Django 3.1.1 on 2020-10-13 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facet_one', '0016_remove_blog_comment'),
        ('comments', '0005_auto_20201013_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercomment',
            name='blug',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facet_one.blog'),
        ),
    ]
