# Generated by Django 3.1.1 on 2020-10-13 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0006_usercomment_blug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercomment',
            old_name='blug',
            new_name='blog',
        ),
    ]
