# Generated by Django 3.1.1 on 2020-10-16 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0008_usercomment_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercomment',
            name='reply',
        ),
        migrations.CreateModel(
            name='UserCommentReplies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.TextField(blank=True, null=True)),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comments.usercomment')),
            ],
        ),
    ]
