# Generated by Django 3.1.1 on 2020-10-16 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0013_usercommentreply_reply_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercommentreply',
            old_name='reply_reply',
            new_name='in_reply_to',
        ),
    ]
