# Generated by Django 3.1.1 on 2020-10-18 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facet_one', '0018_remove_blog_comment'),
        ('comments', '0016_auto_20201017_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercomment',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comments.usercomment'),
        ),
        migrations.AlterField(
            model_name='usercomment',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facet_one.blog'),
        ),
        migrations.DeleteModel(
            name='UserCommentReply',
        ),
    ]
