# Generated by Django 3.1.1 on 2020-10-23 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0019_auto_20201023_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercomment',
            name='likes',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
