# Generated by Django 3.1.1 on 2020-10-24 18:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0020_auto_20201023_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercomment',
            name='comment_added',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='comment added'),
        ),
    ]
