# Generated by Django 3.1.1 on 2020-10-24 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0021_auto_20201024_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercomment',
            name='comment_added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='comment added'),
        ),
    ]
