# Generated by Django 3.1.1 on 2020-10-26 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0024_auto_20201026_0158'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentlikes',
            options={'verbose_name_plural': 'Comment Likes'},
        ),
        migrations.AlterField(
            model_name='commentlikes',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usercomment',
            name='text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
