# Generated by Django 3.1.1 on 2020-10-29 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0025_auto_20201026_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercomment',
            name='likes',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
