# Generated by Django 3.1.1 on 2020-10-01 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facet_one', '0003_auto_20200930_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='body1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='body2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='body3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='body4',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='blog',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='blog',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='blog',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
