# Generated by Django 3.1.1 on 2020-10-02 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facet_one', '0004_auto_20201001_0900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='body1',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='body2',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='body3',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='body4',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='image',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='image4',
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facet_one.blog')),
            ],
        ),
    ]
