# Generated by Django 3.1.1 on 2020-10-11 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facet_one', '0007_auto_20201011_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persons',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='persons',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='persons',
            name='surname',
        ),
    ]
