# Generated by Django 3.1.1 on 2020-10-11 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facet_one', '0009_auto_20201011_1415'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='persons',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='persons',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='persons',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='persons',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='persons',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='persons',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='persons',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='persons',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='persons',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='persons',
            name='user_permissions',
        ),
    ]
