# Generated by Django 3.1.1 on 2020-10-11 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facet_one', '0010_auto_20201011_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='datetime_added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date&time added'),
        ),
    ]
