# Generated by Django 3.1.1 on 2020-10-11 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facet_one', '0011_auto_20201011_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='last_update',
            field=models.CharField(blank=True, default='ekm', max_length=40, null=True),
        ),
    ]
