# Generated by Django 3.1.1 on 2020-10-11 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facet_one', '0012_blog_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
