# Generated by Django 3.1.1 on 2020-10-13 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_auto_20201013_1703'),
        ('facet_one', '0014_auto_20201011_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comments.usercomment'),
        ),
    ]
