# Generated by Django 3.1.1 on 2020-10-13 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facet_one', '0015_blog_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='comment',
        ),
    ]
