# Generated by Django 3.1.1 on 2020-11-01 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facet_one', '0019_auto_20201101_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='enable_comment',
            field=models.IntegerField(choices=[(1, 'enable'), (2, 'disable')], default=1),
        ),
        migrations.AddField(
            model_name='blog',
            name='status',
            field=models.IntegerField(choices=[(1, 'Live'), (2, 'Draft')], default=1),
        ),
    ]
