# Generated by Django 3.1.1 on 2020-11-01 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0001_initial'),
        ('facet_one', '0020_auto_20201101_2251'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlatPageForm',
            fields=[
                ('flatpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flatpages.flatpage')),
            ],
            bases=('flatpages.flatpage',),
        ),
        migrations.AlterField(
            model_name='blog',
            name='enable_comment',
            field=models.IntegerField(choices=[(1, 'enable'), (2, 'disable')]),
        ),
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.IntegerField(choices=[(1, 'Live'), (2, 'Draft')]),
        ),
    ]
