# Generated by Django 3.1.1 on 2020-11-03 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facet_one', '0022_auto_20201103_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_image_description',
            field=models.CharField(blank=True, help_text='serves as the alt attribute of the image tag', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_image',
            field=models.ImageField(blank=True, help_text='the image associated with the blog', null=True, upload_to='blog_images'),
        ),
    ]
