# Generated by Django 3.1.1 on 2020-11-03 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facet_one', '0023_auto_20201103_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_image',
            field=models.ImageField(help_text='the image associated with the blog', null=True, upload_to='blog_images'),
        ),
    ]
