# Generated by Django 3.1.1 on 2020-11-06 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facet_one', '0026_linksvisit_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='descriptor',
            field=models.CharField(blank=True, help_text='link descriptor (homepage, e.t.c)', max_length=50),
        ),
        migrations.AlterField(
            model_name='url',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
