# Generated by Django 3.1.1 on 2020-11-07 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facet_one', '0029_auto_20201106_2120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dates',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='url',
            name='today_date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facet_one.dates'),
        ),
    ]
