# Generated by Django 3.1.1 on 2020-11-07 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facet_one', '0030_auto_20201107_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='today_date',
            field=models.DateField(),
        ),
    ]
