# Generated by Django 3.1.1 on 2020-11-07 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facet_one', '0031_auto_20201107_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='today_date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facet_one.dates'),
        ),
    ]
