# Generated by Django 3.1.1 on 2020-11-07 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facet_one', '0032_auto_20201107_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linksvisit',
            name='today_date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facet_one.dates'),
        ),
    ]
