# Generated by Django 3.1.1 on 2020-11-07 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facet_one', '0033_auto_20201107_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linksvisit',
            name='no_of_visits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
