# Generated by Django 3.1.1 on 2020-11-07 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facet_one', '0034_auto_20201107_0754'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dates',
            options={'verbose_name_plural': 'Dates'},
        ),
        migrations.AlterField(
            model_name='linksvisit',
            name='today_date',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='facet_one.dates'),
        ),
        migrations.AlterField(
            model_name='url',
            name='today_date',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='facet_one.dates'),
        ),
    ]
