# Generated by Django 3.1.1 on 2020-11-08 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facet_one', '0035_auto_20201107_0822'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlCount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('count', models.PositiveIntegerField(default=0)),
                ('date', models.DateField()),
                ('Url', models.CharField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='url',
            name='today_date',
        ),
        migrations.AlterField(
            model_name='dates',
            name='date',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='linksvisit',
            name='today_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='url',
            name='url_visit_count',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='facet_one.urlcount'),
        ),
    ]
