# Generated by Django 3.1.1 on 2020-11-07 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facet_one', '0036_auto_20201108_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlcount',
            name='description',
            field=models.CharField(default='', help_text='link descriptor (homepage, e.t.c)', max_length=50),
        ),
    ]
