# Generated by Django 3.1.1 on 2020-11-08 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facet_one', '0038_auto_20201107_1018'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dates',
        ),
        migrations.DeleteModel(
            name='LinksVisit',
        ),
        migrations.DeleteModel(
            name='Url',
        ),
        migrations.DeleteModel(
            name='UrlCount',
        ),
    ]
