# Generated by Django 3.1.1 on 2020-11-08 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facet_one', '0039_auto_20201108_0940'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinksVisit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('today_date', models.DateField(unique=True)),
                ('no_of_visits', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UrlCount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('count', models.PositiveIntegerField(default=0)),
                ('date', models.DateField()),
                ('Url', models.CharField(max_length=500)),
                ('description', models.CharField(help_text='link descriptor (homepage, e.t.c)', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=500, unique=True)),
                ('descriptor', models.CharField(help_text='link descriptor (homepage, e.t.c)', max_length=50, unique=True)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('url_visit_count', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='facet_one.urlcount')),
            ],
        ),
    ]
