# Generated by Django 3.1.1 on 2020-10-13 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercomment',
            name='text',
            field=models.TextField(blank=True, default='pop'),
        ),
    ]
