# Generated by Django 3.1.1 on 2020-10-16 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0012_auto_20201016_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercommentreply',
            name='reply_reply',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comments.usercommentreply'),
        ),
    ]
