# Generated by Django 3.1.1 on 2020-10-17 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0015_auto_20201017_0111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercomment',
            options={'default_permissions': ('add',)},
        ),
    ]
