# Generated by Django 3.1.1 on 2020-10-23 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0017_auto_20201018_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercomment',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usercomment',
            name='comment_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='comment added'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usercomment',
            name='likes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
