# Generated by Django 3.1.1 on 2020-10-23 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0018_auto_20201023_1718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercomment',
            old_name='comment_time',
            new_name='comment_added',
        ),
        migrations.AlterField(
            model_name='usercomment',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
