# Generated by Django 3.1.1 on 2020-10-11 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facet_one', '0006_image_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persons',
            name='address',
        ),
        migrations.RemoveField(
            model_name='persons',
            name='city',
        ),
    ]
