# Generated by Django 3.1.1 on 2020-11-06 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facet_one', '0024_auto_20201103_1825'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Persons',
        ),
    ]
