# Generated by Django 3.1.1 on 2020-11-06 16:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facet_one', '0025_delete_persons'),
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LinksVisit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('today_date', models.DateField(default=datetime.date.today)),
                ('no_of_visits', models.PositiveIntegerField()),
                ('url_visit_count', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='facet_one.url')),
            ],
        ),
    ]
