# Generated by Django 3.1.1 on 2020-11-06 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facet_one', '0027_auto_20201106_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='descriptor',
            field=models.CharField(help_text='link descriptor (homepage, e.t.c)', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='url',
            name='url',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
